import { IncomeTaxRepository } from "../repositories/income-tax.repository"
import { MonthlyIncomeRepository } from "../repositories/monthly-income.repository"
import { CreateIncomeTaxDTO, UpdateIncomeTaxDTO } from "../dtos/income-tax.dto"

const incomeTaxRepository = new IncomeTaxRepository()
const monthlyIncomeRepository = new MonthlyIncomeRepository()

export class IncomeTaxService {
  async createTax(data: CreateIncomeTaxDTO) {
    const taxType = data.tax_type?.trim()

    if (!taxType || taxType.length === 0) {
      throw new Error("Tax type is required")
    }

    if (data.value < 0) {
      throw new Error("Tax value must be greater than or equal to zero")
    }

    const income = await monthlyIncomeRepository.findById(data.monthly_income_id)
    if (!income) {
      throw new Error("Monthly income not found")
    }

    if (data.is_auto) {
      throw new Error("Automatic income taxes must be generated by the income service")
    }

    return incomeTaxRepository.create({
      ...data,
      tax_type: taxType,
    })
  }

  async findTaxById(id: string) {
    const tax = await incomeTaxRepository.findById(id)
    if (!tax) {
      throw new Error("Income tax not found")
    }
    return tax
  }

  async listTaxesByIncome(monthlyIncomeId: string) {
    return incomeTaxRepository.findByMonthlyIncomeId(monthlyIncomeId)
  }

  async updateTax(id: string, data: UpdateIncomeTaxDTO) {
    const existingTax = await incomeTaxRepository.findById(id)
    if (!existingTax) {
      throw new Error("Income tax not found")
    }

    if (existingTax.getDataValue("is_auto") as boolean) {
      throw new Error("Automatic income taxes cannot be edited manually")
    }

    const normalizedTaxType = data.tax_type?.trim()

    if (data.tax_type !== undefined && (!normalizedTaxType || normalizedTaxType.length === 0)) {
      throw new Error("Tax type is required")
    }

    if (data.value !== undefined && data.value < 0) {
      throw new Error("Tax value must be greater than or equal to zero")
    }

    const tax = await incomeTaxRepository.update(id, {
      ...data,
      is_auto: false,
      tax_type: normalizedTaxType,
    })
    if (!tax) {
      throw new Error("Income tax not found")
    }
    return tax
  }

  async deleteTax(id: string) {
    const existingTax = await incomeTaxRepository.findById(id)
    if (!existingTax) {
      throw new Error("Income tax not found")
    }

    if (existingTax.getDataValue("is_auto") as boolean) {
      throw new Error("Automatic income taxes cannot be deleted manually")
    }

    const tax = await incomeTaxRepository.delete(id)
    if (!tax) {
      throw new Error("Income tax not found")
    }
    return tax
  }
}
