import type { CreateIncomeTaxDTO } from "../../../dtos/income-tax.dto";
import type { IIncomeTaxRepository } from "../../../domain/repositories/income-tax.repository";
import type { IMonthlyIncomeRepository } from "../../../domain/repositories/monthly-income.repository";
import { ForbiddenError } from "../../../utils/errors";

export class CreateIncomeTaxUseCase {
  constructor(
    private readonly incomeTaxRepository: IIncomeTaxRepository,
    private readonly monthlyIncomeRepository: IMonthlyIncomeRepository,
  ) {}

  async execute(data: CreateIncomeTaxDTO, requestingUserId: string) {
    const taxType = data.tax_type?.trim();

    if (!taxType || taxType.length === 0) {
      throw new Error("Tax type is required");
    }

    if (data.value < 0) {
      throw new Error("Tax value must be greater than or equal to zero");
    }

    const income = await this.monthlyIncomeRepository.findById(
      data.monthly_income_id,
    );
    if (!income) {
      throw new Error("Monthly income not found");
    }

    if (income.user.id !== requestingUserId) {
      throw new ForbiddenError();
    }

    if (data.is_auto) {
      throw new Error(
        "Automatic income taxes must be generated by the income service",
      );
    }

    return this.incomeTaxRepository.create({
      monthlyIncomeId: data.monthly_income_id,
      taxType: taxType,
      value: data.value,
      isAuto: false,
    });
  }
}
